### ISSUE TITLE
Training fails on macOS

### ISSUE THREAD

**Issue by gkowalski** [stanfordnlp/stanza-train#1]
Ran thru your README : 

git clone https://github.com/stanfordnlp/stanza-train.git
cd stanza-train
git clone https://github.com/stanfordnlp/stanza.git
cp config/config.sh stanza/scripts/config.sh
cp config/xpos_vocab_factory.py stanza/stanza/models/pos/xpos_vocab_factory.py
cd stanza

then : 
$  bash scripts/run_tokenize.sh UD_English-TEST --step 500
scripts/treebank_to_shorthand.sh: line 7: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
scripts/treebank_to_shorthand.sh: line 7: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
Preparing tokenizer train data...
Traceback (most recent call last):
  File "stanza/utils/prepare_tokenizer_data.py", line 16, in <module>
    with open(args.plaintext_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../data/udbase/UD_English-TEST/wo_test-ud-train.txt'
cp: ../data/udbase/UD_English-TEST/wo_test-ud-train.conllu: No such file or directory
cp: ../data/udbase/UD_English-TEST/wo_test-ud-train.txt: No such file or directory
scripts/treebank_to_shorthand.sh: line 7: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
Preparing tokenizer dev data...
Traceback (most recent call last):
  File "stanza/utils/prepare_tokenizer_data.py", line 16, in <module>
    with open(args.plaintext_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../data/udbase/UD_English-TEST/wo_test-ud-dev.txt'
cp: ../data/udbase/UD_English-TEST/wo_test-ud-dev.conllu: No such file or directory
cp: ../data/udbase/UD_English-TEST/wo_test-ud-dev.txt: No such file or directory
... 

The file in the test data starts with "en" as en_test-ud-dev.conllu not "wo" .

**Comment by gkowalski** [comment]
I'm on a mac with latest os and stock bash 

(venv) ➜  stanza git:(master) ✗ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.
(venv) ➜  stanza git:(master) ✗

**Comment by yuhui-zh15** [comment]
Thank you for reporting this problem! This problem is occurred because of syntax differences between macOS and Linux. 

The syntax `declare -A` in the script `scripts/treebank_to_shorthand.sh` is [not supported](https://stackoverflow.com/questions/27002192/bash-declare-a-does-not-work-on-macos) in macOS. 

Running on Linux should not have such problem. If you still want to run on macOS, you probably have to modify the `scripts/treebank_to_shorthand.sh`.

**Comment by gkowalski** [comment]
Has issues with the pr command also on mac. I have it working under a Linux VM. I suggest you update your README to reflect this only works under linux , saving others time and effort. 

Thanks

G
