### ISSUE TITLE
How to train sentiment model

### ISSUE THREAD

**Issue by ab-star** [stanfordnlp/stanza-train#13]
Hello ,

Could any let know what is the correct format of data to train sentiment mode and the way to train it?

how to train it for few scentences or words?
as i want different results for some scentences or words,

 Thank you

**Comment by AngledLuffa** [comment]
https://github.com/stanfordnlp/stanza/issues/1046

**Comment by AngledLuffa** [comment]
Look in the dev branch of stanza (you can install the dev branch or git clone the repo to access these scripts)

https://github.com/stanfordnlp/stanza/blob/dev/stanza/utils/datasets/sentiment/prepare_sentiment_dataset.py

https://github.com/stanfordnlp/stanza/blob/dev/stanza/utils/training/run_sentiment.py
