### ISSUE TITLE
Which charlm used when training NER?

### ISSUE THREAD

**Issue by lpossberg** [stanfordnlp/stanza-train#3]
Hello,

I want to train the ner tagger on my own entity type. I am using the following command in which I do not provide my own charlm.
```
scripts/run_ner.sh German-MyBase --lang de --lr 0.01 --max_steps 5000 --dropout 0.2
```

The INFO on the console shows me:
```
2020-09-17 15:04:53 INFO: NERTagger(
  (word_emb): Embedding(100000, 100, padding_idx=0)
  (charmodel): CharacterModel(
    (char_emb): Embedding(112, 100, padding_idx=0)
    (charlstm): PackedLSTM(
      (lstm): LSTM(100, 100, batch_first=True, bidirectional=True)
    )
    (dropout): Dropout(p=0.2, inplace=False)
  )
  (input_transform): Linear(in_features=300, out_features=300, bias=True)
  (taggerlstm): PackedLSTM(
    (lstm): LSTM(300, 256, batch_first=True, bidirectional=True)
  )
  (tag_clf): Linear(in_features=512, out_features=17, bias=True)
  (crit): CRFLoss()
  (drop): Dropout(p=0.2, inplace=False)
  (worddrop): WordDropout(p=0)
  (lockeddrop): LockedDropout(p=0.0)
)
```
From lines 3-9 it seems to me that a charlm is present. I am wondering what that means. Why is it present, even though I did not pass the parameter? Is it a blank charlm and will be trained? Or is it a default pre-trained one from stanza?

Ideally I would not want to train one, but use one from stanza, is it available/possible?

Thanks for the answers!

**Comment by lpossberg** [comment]
After training I did
```python
import stanza
nlp = stanza.Pipeline(lang='de', dir='path/to/downloaded/models', ner_model_path='path/to/my/trained/model/de_mybase_nertagger.pt')
nlp.config
```
which printed me:
```
{'tokenize_model_path': 'path/to/downloaded/models/de/tokenize/gsd.pt', 
'mwt_model_path': 'path/to/downloaded/models/de/mwt/gsd.pt', 
'pos_model_path': 'path/to/downloaded/models/de/pos//gsd.pt',
'pos_pretrain_path': 'path/to/downloaded/models/de/pretrain/gsd.pt',
'lemma_model_path': 'path/to/downloaded/models/de/lemma/gsd.pt', 
'depparse_model_path': 'path/to/downloaded/models/de/depparse/gsd.pt', 
'depparse_pretrain_path': 'path/to/downloaded/models/de/pretrain/gsd.pt', 
'sentiment_model_path': 'path/to/downloaded/models/de/sentiment/sb10k.pt', 
'sentiment_pretrain_path': 'path/to/downloaded/models/de/pretrain/gsd.pt', 
'ner_model_path': 'path/to/my/trained/model/de_mybase_nertagger.pt', 
'ner_forward_charlm_path': 'path/to/downloaded/models/de/forward_charlm/newswiki.pt', 
'ner_backward_charlm_path': 'path/to/downloaded/models/de/backward_charlm/newswiki.pt'}
```
Judging by the last three lines of the output it seems that it worked as I wanted to. My trained NER model is in the `Pipeline` and there is also a model for the `forward_charlm` and one for the `backward_charlm`. 

Do I have to give `path/to/downloaded/models/de/forward_charlm/newswiki.pt` and `path/to/downloaded/models/de/backward_charlm/newswiki.pt` as arguements for forward/backward charlm when training with `scripts/run_ner.sh`?

**Comment by AngledLuffa** [comment]
Older issue, but to answer it for posterity: the charlms for each NER model are documented in the resources.json file that gets downloaded when you download the NER models
