### ISSUE TITLE
Could you describe what settings the production stanza English model is trained with?

### ISSUE THREAD

**Issue by swartchris8** [stanfordnlp/stanza-train#4]
I would like to train a custom NER component using the production stanza English model - based on this tutorial it is not clear to me how to do this.

I am confused if the production stanza en model uses charlm or just word2vec. Based on the [training documentation](https://stanfordnlp.github.io/stanza/training.html) it seems to use word2vec but here you suggest using a charlm for better performance

Is the training documentation out of date? I also noticed that this repo only describes how to run a test example while the traning docs give a more complete picture. 

I will initially just do a word2vec based NER model and see if I can add the charlm step once I get this simpler approach working.

**Comment by AngledLuffa** [comment]
Sorry, do you mean starting from the existing one or retrain a new model
entirely?

**Comment by swartchris8** [comment]
Either of this would be useful

**Comment by AngledLuffa** [comment]
Probably something like this:

python3 -m stanza.models.ner_tagger --wordvec_pretrain_file saved_models/pos/fi_ftb.pretrain.pt --train_file data/ner/fi_turku.train.json --eval_file data/ner/fi_turku.dev.json --lang fi --charlm --charlm_shorthand fi_conll17 --shorthand fi_turku --mode train --char_hidden_dim 1024 

The conll and ontonotes both use the en_1billion charlms.  The conll ner used the glove word vectors, and the ontonotes used the fasttext.

You can use the --finetune parameter to do transfer learning:

9bd6c38f29ce6b5a9867ad6ddec0a77a34c4f431
