### ISSUE TITLE
Cannot train your example...

### ISSUE THREAD

**Issue by rjgarciar** [stanfordnlp/stanza-train#6]
Hi, 

I'm trying to train your test samples with:

`bash scripts/run_ner.sh English-TEST --max_steps 500 --word_emb_dim 5`

but it fails in run_ner.sh:

`if [ ! -e $train_file ]; then
    bash scripts/prep_ner_data.sh $corpus
fi`

because no prep_ner_data.sh exists anywhere in your repositories.

Regards,
Ramón García

**Comment by AngledLuffa** [comment]
Short answer is that documentation is out of date.  Look here at the
subsection titled "run ner_tagger directly":

https://stanfordnlp.github.io/stanza/training.html#training-with-scripts

You can also build the data yourself first, then comment out the lines
regarding building the data in run_ner.sh

I'll put something together tonight in the form of an updated python script

**Comment by AngledLuffa** [comment]
There's a new run_ner.py script here:

https://github.com/stanfordnlp/stanza/blob/run_ner/stanza/utils/training/run_ner.py

**Comment by rjgarciar** [comment]
Thanks, I'll try with it

**Comment by rjgarciar** [comment]
Thanks

In the end I was able to train your example using run_ner.py
