### ISSUE TITLE
AssertionError: Unable to process treebanks

### ISSUE THREAD

**Issue by VasilisTz1** [stanfordnlp/stanza-train#7]
Hello, 

I followed your guide and I am trying to run the basic example with the UD_English-TEST data. However, when I run the following command:

`python ./stanza/stanza/utils/datasets/prepare_tokenizer_treebank.py treebanks ./data/udbase/UD_English-EWT`

I get this error:

`File "/home/mypc/pythonenv/stanza_env/lib/python3.8/site-packages/stanza/models/common/constant.py", line 170, in treebank_to_short_name
    assert len(splits) == 2, "Unable to process %s" % treebank
AssertionError: Unable to process treebanks`

Thank you in advance

**Comment by AngledLuffa** [comment]
Surely that is supposed to be --treebanks and not just treebanks without
the dashes.  If there's a bit of doc which tells you to use it without the
-- please let us know and we'll fix it

Anyway, I recommend trying the newer scripts:

https://stanfordnlp.github.io/stanza/training.html#converting-ud-data

**Comment by VasilisTz1** [comment]
Thank you for your reply!

Following your link, I found that the ${module} for tokenizer should be "tokenizer", with the "r" at the end.

I would like to train a model for a new language. Following https://stanfordnlp.github.io/stanza/new_language.html , I have to go back to your link. However,  I get an error, as my language is not recognized.

`File "/home/mypc/pythonenv/stanza_env/lib/python3.8/site-packages/stanza/models/common/constant.py", line 180, in treebank_to_short_name
    raise ValueError("Unable to find language code for %s" % lang)
ValueError: Unable to find language code for Mylanguage`

**Comment by AngledLuffa** [comment]
Are you saying "my" as in Myanmar is not recognized, or "my" as in some
other language is not recognized?  Myanmar should be recognized, but other
languages might need code changes to properly process them.  If it's a
previous unhandled language, please let us know and we'll add that right
away.  If it's a rebuild of an existing stana language on a new dataset,
you want to reuse the same language code: en_newdataset, for example.

**Comment by VasilisTz1** [comment]
Thank you for your immediate response!

I am talking about a language that is not widely known. I would like some guidance for these "code changes" and the whole process in general, if possible.

**Comment by AngledLuffa** [comment]
I can think of at least two or three places which are relevant.  Continuing with the Myanmar example, I grepped for that in our codebase.  There's two maps where we map language code to the language name:

```
stanza/models/common/constant.py:    "my": "Myanmar",
stanza/resources/prepare_resources.py:    "my": "Myanmar",
```

This is something I want to merge into one map, btw.

If you get to the point where you're training a pos tagger, there also needs to be an addition to this:

```
stanza/models/pos/build_xpos_vocab_factory.py
```

Including that in the model itself is something that's been on my list, so if it winds up being a sticking point, please let us know and I'll move that higher in the todo list.

Let me know if this helps or if you get stuck.  Once there's some progress, I'll add that to the documentation, since it's clearly a missing component of the doc.

**Comment by VasilisTz1** [comment]
Thank you for your guidance! I finally trained my **tokenize**, **lemma**, and **pos** processors. However... 

There isn't information for dependencies in my data yet. As a result, I had to do **manual** changes to the code for this reason... For example in `/lib/python3.8/site-packages/stanza/utils/conll.py`, line 24, from:

`FIELD_TO_IDX = {ID: 0, TEXT: 1, LEMMA: 2, UPOS: 3, XPOS: 4, FEATS: 5, HEAD: 6, DEPREL: 7, DEPS: 8, MISC: 9}`

changed to:

`FIELD_TO_IDX = {ID: 0, TEXT: 1, LEMMA: 2, UPOS: 3, XPOS: 4, FEATS: 5}`

Is any easier way to disable the dependencies request?

**Comment by AngledLuffa** [comment]
Maybe fake dependency information, such as putting 0, 1, 2, 3, ... in the
dependency fields
